[package]
name = "ratatui_json_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.26.3"
serde = { version = "1.0.203", features = ["derive"]}
serde_json = "1.0.117"
