[package]
name = "terminal_size_change_test"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
kernel32-sys = "0.2.2"
winapi = { version = "0.3.9", features = ["consoleapi", "wincon", "wincontypes", "minwindef"] }
